name: tests

on:
  push:
    paths-ignore:
      - "README.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: carbo build --verbose

    - name: Run Tests
      run: cargo test --verbose
